# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "29efab96cbb03baffd0e8578052393e9"
name = "VDCStore MarketPlace"
application_url = "https://db048f1d24e8.ngrok-free.app"
embedded = false

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,write_fulfillments,read_orders,write_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
"https://db048f1d24e8.ngrok-free.app",
"https://db048f1d24e8.ngrok-free.app/callback",
"https://db048f1d24e8.ngrok-free.app/install"
]

[app_preferences]
url = "https://db048f1d24e8.ngrok-free.app"
